name: Publish Docker image

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: GitFabien/platform-demo-lab1/.github/workflows/thedasken/ci.yml@main
